### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by pjastr** [mgorcz2/TerminalProject#3]

**Comment by pjastr** [comment]
Sprawdzę w wolniejszej chwili, na razie sprawdzam inżynierki :(

**Comment by mgorczynsky2** [comment]
Jeszcze nie skończone jakby co, narazie wiecej zabawy niz pożytku, ale pomyslalem ze już dodam :D

**Comment by pjastr** [comment]
Obecnie na profilu mam ponad 10k repozytoriów, więc wolę zrobić sobie issue w koszyku by nie zgubić.

**Comment by pjastr** [comment]
Przepraszam za długi czas bez odpowiedzi, ale jakoś zapomniałem, a teraz czyszczę listę issue i dopiero zobaczyłem.

Jak na pierwszy projekt jest ok, ale kod powinien być lepiej podzielony.

Proponuje poczytać sobie o wzorcach projektowych https://refactoring.guru/pl/design-patterns

Należy też odseparować też logikę wykonywania czynności od samych formularz. W klasach Forms1 i Forms2 nie powinno być za dużo logiki/definicji metod. One powinny być przeniesione do innych klas, tak aby logika mogła by być "uniwersalna" przy różnych formsach. Może przy małym projekcie to trochę słabo widać.
